spring.application.name=empmanagement

server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/emp_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration (1 hour = 3600000ms)
jwt.secret=55d28892f3cbdb0579178351b88e14b2d35c4e97666cd08d17a3a41c4ebcf0f0
jwt.expiration=3600000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.hexagon.empmanagement=DEBUG
